# Makefile: Makefile to synthesize module
# Copyright (C) 2026 Universitaet Heidelberg, Institut fuer Technische Informatik (ZITI)
# Author(s): Vladislav Valek <vladislav.valek@stud.uni-heidelberg.de>
#
# SPDX-License-Identifier: Apache-2.0

TOP_LEVEL_ENT=H2C_DMA_HYPERION
TOP_LEVEL_PATH=..

SYNTH=vivado

CLK_PORTS=CLK
CLK_PERIOD=4.000

.PHONY: all
all: comp

include ../../../../../../../build/Makefile
