# Makefile: for synthesizing the compoments
# Copyright 2024 Universitaet Heidelberg, Institut fuer Technische Informatik (ZITI)
# Author(s): Vladislav Valek <vladislavwalek@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

TOP_LEVEL_ENT=UPDOWN_CNTR
TOP_LEVEL_PATH=..

SYNTH=vivado

CLK_PORTS=CLK
CLK_PERIOD=4.000

.PHONY: all
all: comp

include ../../../../src/ofm/build/Makefile
