-- combo_user_const_pkg.vhd: minimal stand-in for the per-card `combo_user_const` package
-- Copyright (C) 2026 Universitaet Heidelberg, Institut fuer Technische Informatik (ZITI)
-- Author(s): Vladislav Valek <vladislav.valek@stud.uni-heidelberg.de>
--
-- SPDX-License-Identifier: CERN-OHL-W-2.0

-- Stub for the per-card `combo_user_const` package (normally generated by the NDK core build).
-- USER_CORE only has a bare `use work.combo_user_const.all;` clause and reads nothing from it,
-- so this standalone testbench needs only an empty package.

package combo_user_const is
end package;
