# Makefile: Makefile to compile module
# Copyright (C) 2025 Universitaet Heidelberg, Institut fuer Technische Informatik (ZITI)
# Author(s): Vladislav Valek <vladislav.valek@stud.uni-heidelberg.de>
#
# SPDX-License-Identifier: Apache-2.0

TOP_LEVEL_ENT=NVME_CMD_DISPATCHER_MI32
TOP_LEVEL_PATH=..

SYNTH=vivado

CLK_PORTS=CLK
CLK_PERIOD=4.000

.PHONY: all
all: comp

include ../../../../build/Makefile
